languageCode = "en-us"
relativeURLs = true
title = "Cody's Portfolio"
theme = "basic"
[params]
  author = "Cody Stair"
  description = "My Portfolio Site"

  gh_url = "https://api.github.com/users"
  gh_user = "codystair"
